# Generated by Django 5.1.2 on 2024-10-26 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir_kolbass', '0003_alter_about_description_alter_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(7)], verbose_name='Номер телефона')),
                ('facebook_list', models.URLField(blank=True, verbose_name='Ссылка на Facebook')),
                ('instagram_list', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
