# Generated by Django 5.1.2 on 2024-10-27 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir_kolbass', '0004_socialmediacontact_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediacontact',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Номер телефона'),
        ),
    ]
