# Generated by Django 5.1.2 on 2024-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir_kolbass', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='composition',
            field=models.CharField(default=1, max_length=200, verbose_name='состав'),
            preserve_default=False,
        ),
    ]
